DEFAULT_BOARD_SETUP = """[
    { "name": "Bohemia", "abbr": "BOH", "owner": "AUSTRIA", "province_type": "INLAND", "supply_center": "false", "neighbors": [ "SIL", "MUN", "TYR", "VIE", "GAL" ] },
    { "name": "Budapest", "abbr": "BUD", "owner": "AUSTRIA", "province_type": "INLAND", "supply_center": "true", "neighbors": [ "GAL", "VIE", "TRI", "SER", "RUM" ] },
    { "name": "Galicia", "abbr": "GAL", "owner": "AUSTRIA", "province_type": "INLAND", "supply_center": "false", "neighbors": [ "WAR", "SIL", "BOH", "VIE", "BUD", "RUM", "UKR" ] },
    { "name": "Trieste", "abbr": "TRI", "owner": "AUSTRIA", "province_type": "COASTAL", "supply_center": "true", "neighbors": [ "VIE", "TYR", "VEN", "ADR", "ALB", "SER", "BUD" ] },
    { "name": "Tyrolia", "abbr": "TYR", "owner": "AUSTRIA", "province_type": "INLAND", "supply_center": "false", "neighbors": [ "MUN", "PIE", "VEN", "TRI", "VIE", "BOH" ] },
    { "name": "Vienna", "abbr": "VIE", "owner": "AUSTRIA", "province_type": "INLAND", "supply_center": "true", "neighbors": [ "BOH", "TYR", "TRI", "BUD", "GAL" ] },
    { "name": "Clyde", "abbr": "CLY", "owner": "ENGLAND", "province_type": "COASTAL", "supply_center": "false", "neighbors": [ "NAT", "LVP", "EDI", "NRG" ] },
    { "name": "Edinburgh", "abbr": "EDI", "owner": "ENGLAND", "province_type": "COASTAL", "supply_center": "true", "neighbors": [ "NRG", "CLY", "LVP", "YOR", "NTH" ] },
    { "name": "Liverpool", "abbr": "LVP", "owner": "ENGLAND", "province_type": "COASTAL", "supply_center": "true", "neighbors": [ "CLY", "NAT", "IRI", "WAL", "YOR", "EDI" ] },
    { "name": "London", "abbr": "LON", "owner": "ENGLAND", "province_type": "COASTAL", "supply_center": "true", "neighbors": [ "YOR", "WAL", "ENG", "NTH" ] },
    { "name": "Wales", "abbr": "WAL", "owner": "ENGLAND", "province_type": "COASTAL", "supply_center": "false", "neighbors": [ "LVP", "IRI", "WAL", "LON", "YOR", "ENG" ] },
    { "name": "Yorkshire", "abbr": "YOR", "owner": "ENGLAND", "province_type": "COASTAL", "supply_center": "false", "neighbors": [ "EDI", "LVP", "WAL", "LON", "NTH" ] },
    { "name": "Brest", "abbr": "BRE", "owner": "FRANCE", "province_type": "COASTAL", "supply_center": "true", "neighbors": [ "ENG", "MID", "GAS", "PAR", "PIC" ] },
    { "name": "Burgundy", "abbr": "BUR", "owner": "FRANCE", "province_type": "INLAND", "supply_center": "false", "neighbors": [ "BEL", "PIC", "PAR", "GAS", "MAR", "MUN", "RUH" ] },
    { "name": "Gascony", "abbr": "GAS", "owner": "FRANCE", "province_type": "COASTAL", "supply_center": "false", "neighbors": [ "BRE", "MID", "SPA", "MAR", "BUR", "PAR" ] },
    { "name": "Marseilles", "abbr": "MAR", "owner": "FRANCE", "province_type": "INLAND", "supply_center": "true", "neighbors": [ "BUR", "GAS", "SPA", "GOL", "PIE" ] },
    { "name": "Paris", "abbr": "PAR", "owner": "FRANCE", "province_type": "INLAND", "supply_center": "true", "neighbors": [ "PIC", "BRE", "GAS", "BUR" ] },
    { "name": "Picardy", "abbr": "PIC", "owner": "FRANCE", "province_type": "COASTAL", "supply_center": "false", "neighbors": [ "ENG", "BRE", "PAR", "BUR", "BEL" ] },
    { "name": "Berlin", "abbr": "BER", "owner": "GERMANY", "province_type": "COASTAL", "supply_center": "true", "neighbors": [ "BAL", "KIE", "MUN", "SIL", "PRU" ] },
    { "name": "Kiel", "abbr": "KIE", "owner": "GERMANY", "province_type": "COASTAL", "supply_center": "true", "neighbors": [ "HEL", "HOL", "RUH", "MUN", "BER", "BAL", "DEN" ] },
    { "name": "Munich", "abbr": "MUN", "owner": "GERMANY", "province_type": "INLAND", "supply_center": "true", "neighbors": [ "BER", "KIE", "RUH", "BUR", "TYR", "BOH", "SIL" ] },
    { "name": "Prussia", "abbr": "PRU", "owner": "GERMANY", "province_type": "COASTAL", "supply_center": "false", "neighbors": [ "BAL", "BER", "SIL", "WAR", "LVN" ] },
    { "name": "Ruhr", "abbr": "RUH", "owner": "GERMANY", "province_type": "INLAND", "supply_center": "false", "neighbors": [ "KIE", "HOL", "BEL", "BUR", "MUN" ] },
    { "name": "Silesia", "abbr": "SIL", "owner": "GERMANY", "province_type": "INLAND", "supply_center": "false", "neighbors": [ "BER", "MUN", "BOH", "GAL", "WAR", "PRU" ] },
    { "name": "Apulia", "abbr": "APU", "owner": "ITALY", "province_type": "COASTAL", "supply_center": "false", "neighbors": [ "ADR", "VEN", "ROM", "NAP", "ION" ] },
    { "name": "Naples", "abbr": "NAP", "owner": "ITALY", "province_type": "COASTAL", "supply_center": "true", "neighbors": [ "APU", "ROM", "TYN", "ION" ] },
    { "name": "Piedmont", "abbr": "PIE", "owner": "ITALY", "province_type": "COASTAL", "supply_center": "false", "neighbors": [ "MAR", "GOL", "TUS", "VEN", "TYR" ] },
    { "name": "Rome", "abbr": "ROM", "owner": "ITALY", "province_type": "COASTAL", "supply_center": "true", "neighbors": [ "VEN", "TUS", "TYN", "NAP", "APU" ] },
    { "name": "Tuscany", "abbr": "TUS", "owner": "ITALY", "province_type": "COASTAL", "supply_center": "false", "neighbors": [ "VEN", "PIE", "GOL", "TYN", "ROM" ] },
    { "name": "Venice", "abbr": "VEN", "owner": "ITALY", "province_type": "COASTAL", "supply_center": "true", "neighbors": [ "TYR", "PIE", "TUS", "ROM", "APU", "ADR", "TRI" ] },
    { "name": "Finland", "abbr": "FIN", "owner": "RUSSIA", "province_type": "COASTAL", "supply_center": "false", "neighbors": [ "NWY", "SWE", "BOT", "STP" ] },
    { "name": "Livonia", "abbr": "LVN", "owner": "RUSSIA", "province_type": "COASTAL", "supply_center": "false", "neighbors": [ "BOT", "BAL", "PRU", "WAR", "MOS", "STP" ] },
    { "name": "Moscow", "abbr": "MOS", "owner": "RUSSIA", "province_type": "INLAND", "supply_center": "true", "neighbors": [ "STP", "LVN", "WAR", "UKR", "SEV" ] },
    { "name": "Sevastopol", "abbr": "SEV", "owner": "RUSSIA", "province_type": "COASTAL", "supply_center": "false", "neighbors": [ "MOS", "UKR", "RUM", "BLA", "ARM" ] },
    { "name": "St. Petersburg", "abbr": "STP", "owner": "RUSSIA", "province_type": "COASTAL", "supply_center": "true", "neighbors": [ "BAR", "NWY", "FIN", "BOT", "LVN", "MOS" ] },
    { "name": "Ukraine", "abbr": "UKR", "owner": "RUSSIA", "province_type": "INLAND", "supply_center": "false", "neighbors": [ "MOS", "WAR", "GAL", "RUM", "SEV" ] },
    { "name": "Warsaw", "abbr": "WAR", "owner": "RUSSIA", "province_type": "INLAND", "supply_center": "true", "neighbors": [ "PRU", "SIL", "GAL", "UKR", "MOS", "LVN" ] },
    { "name": "Ankara", "abbr": "ANK", "owner": "TURKEY", "province_type": "COASTAL", "supply_center": "true", "neighbors": [ "BLA", "CON", "SMY", "ARM" ] },
    { "name": "Armenia", "abbr": "ARM", "owner": "TURKEY", "province_type": "COASTAL", "supply_center": "false", "neighbors": [ "SEV", "BLA", "ANK", "SMY", "SYR" ] },
    { "name": "Constantinople", "abbr": "CON", "owner": "TURKEY", "province_type": "COASTAL", "supply_center": "true", "neighbors": [ "BLA", "BUL", "AEG", "SMY", "ANK" ] },
    { "name": "Smyrna", "abbr": "SMY", "owner": "TURKEY", "province_type": "COASTAL", "supply_center": "true", "neighbors": [ "CON", "AEG", "EAS", "SYR", "ARM", "ANK" ] },
    { "name": "Syria", "abbr": "SYR", "owner": "TURKEY", "province_type": "COASTAL", "supply_center": "false", "neighbors": [ "ARM", "SMY", "EAS" ] },
    { "name": "Albania", "abbr": "ALB", "owner": "NEUTRAL", "province_type": "COASTAL", "supply_center": "false", "neighbors": [ "TRI", "ADR", "ION", "GRE", "SER" ] },
    { "name": "Belgium", "abbr": "BEL", "owner": "NEUTRAL", "province_type": "COASTAL", "supply_center": "true", "neighbors": [ "NTH", "ENG", "PIC", "BUR", "RUH", "HOL" ] },
    { "name": "Bulgaria", "abbr": "BUL", "owner": "NEUTRAL", "province_type": "COASTAL", "supply_center": "true", "neighbors": [ "RUM", "SER", "GRE", "AEG", "CON", "BLA" ] },
    { "name": "Denmark", "abbr": "DEN", "owner": "NEUTRAL", "province_type": "COASTAL", "supply_center": "true", "neighbors": [ "SKA", "NTH", "HEL", "KIE", "BAL", "SWE" ] },
    { "name": "Greece", "abbr": "GRE", "owner": "NEUTRAL", "province_type": "COASTAL", "supply_center": "false", "neighbors": [ "SER", "ALB", "ION", "AEG", "BUL" ] },
    { "name": "Holland", "abbr": "HOL", "owner": "NEUTRAL", "province_type": "COASTAL", "supply_center": "true", "neighbors": [ "NTH", "BEL", "RUH", "KIE", "HEL" ] },
    { "name": "Norway", "abbr": "NWY", "owner": "NEUTRAL", "province_type": "COASTAL", "supply_center": "true", "neighbors": [ "NRG", "NTH", "SKA", "SWE", "FIN", "STP", "BAR" ] },
    { "name": "North Africa", "abbr": "NAF", "owner": "NEUTRAL", "province_type": "COASTAL", "supply_center": "false", "neighbors": [ "WES", "MID", "TUN" ] },
    { "name": "Portugal", "abbr": "POR", "owner": "NEUTRAL", "province_type": "COASTAL", "supply_center": "true", "neighbors": [ "MID", "SPA" ] },
    { "name": "Rumania", "abbr": "RUM", "owner": "NEUTRAL", "province_type": "COASTAL", "supply_center": "true", "neighbors": [ "UKR", "GAL", "BUD", "SER", "BUL", "BLA", "SEV" ] },
    { "name": "Serbia", "abbr": "SER", "owner": "NEUTRAL", "province_type": "INLAND", "supply_center": "true", "neighbors": [ "BUD", "TRI", "ALB", "GRE", "BUL", "RUM" ] },
    { "name": "Spain", "abbr": "SPA", "owner": "NEUTRAL", "province_type": "COASTAL", "supply_center": "true", "neighbors": [ "MID", "POR", "WES", "GOL", "MAR", "GAS" ] },
    { "name": "Sweden", "abbr": "SWE", "owner": "NEUTRAL", "province_type": "COASTAL", "supply_center": "true", "neighbors": [ "NWY", "SKA", "DEN", "BAL", "BOT", "FIN" ] },
    { "name": "Tunis", "abbr": "TUN", "owner": "NEUTRAL", "province_type": "COASTAL", "supply_center": "true", "neighbors": [ "TYN", "WES", "NAF", "ION" ] },
    { "name": "Adriatic Sea", "abbr": "ADR", "owner": "NEUTRAL", "province_type": "WATER", "supply_center": "false", "neighbors": [ "VEN", "APU", "ION", "ALB", "TRI" ] },
    { "name": "Aegean Sea", "abbr": "AEG", "owner": "NEUTRAL", "province_type": "WATER", "supply_center": "false", "neighbors": [ "BUL", "GRE", "ION", "EAS", "SMY", "CON", "BLA" ] },
    { "name": "Baltic Sea", "abbr": "BAL", "owner": "NEUTRAL", "province_type": "WATER", "supply_center": "false", "neighbors": [ "SWE", "DEN", "KIE", "BER", "PRU", "LVN", "BOT", "HEL" ] },
    { "name": "Barents Sea", "abbr": "BAR", "owner": "NEUTRAL", "province_type": "WATER", "supply_center": "false", "neighbors": [ "NRG", "NWY", "STP" ] },
    { "name": "Black Sea", "abbr": "BLA", "owner": "NEUTRAL", "province_type": "WATER", "supply_center": "false", "neighbors": [ "SEV", "RUM", "BUL", "AEG", "CON", "ANK", "ARM" ] },
    { "name": "Eastern Mediterranean", "abbr": "EAS", "owner": "NEUTRAL", "province_type": "WATER", "supply_center": "false", "neighbors": [ "SMY", "AEG", "ION", "SYR" ] },
    { "name": "English Channel", "abbr": "ENG", "owner": "NEUTRAL", "province_type": "WATER", "supply_center": "false", "neighbors": [ "WAL", "IRI", "MID", "BRE", "PIC", "BEL", "NTH", "LON" ] },
    { "name": "Gulf of Bothnia", "abbr": "BOT", "owner": "NEUTRAL", "province_type": "WATER", "supply_center": "false", "neighbors": [ "SWE", "BAL", "LVN", "STP", "FIN" ] },
    { "name": "Gulf of Lyon", "abbr": "GOL", "owner": "NEUTRAL", "province_type": "WATER", "supply_center": "false", "neighbors": [ "MAR", "SPA", "WES", "TYN", "TUS", "PIE" ] },
    { "name": "Helgoland Blight", "abbr": "HEL", "owner": "NEUTRAL", "province_type": "WATER", "supply_center": "false", "neighbors": [ "NTH", "HOL", "KIE", "BAL", "DEN" ] },
    { "name": "Ionian Sea", "abbr": "ION", "owner": "NEUTRAL", "province_type": "WATER", "supply_center": "false", "neighbors": [ "ADR", "APU", "NAP", "TYN", "TUN", "EAS", "AEG", "GRE", "ALB" ] },
    { "name": "Irish Sea", "abbr": "IRI", "owner": "NEUTRAL", "province_type": "WATER", "supply_center": "false", "neighbors": [ "NAT", "MID", "ENG", "WAL", "LVP" ] },
    { "name": "Mid-Atlantic Ocean", "abbr": "MID", "owner": "NEUTRAL", "province_type": "WATER", "supply_center": "false", "neighbors": [ "NAT", "NAF", "WES", "SPA", "POR", "GAS", "BRE", "ENG", "IRI" ] },
    { "name": "North Atlantic Ocean", "abbr": "NAT", "owner": "NEUTRAL", "province_type": "WATER", "supply_center": "false", "neighbors": [ "MID", "IRI", "LVP", "CLY", "NRG" ] },
    { "name": "North Sea", "abbr": "NTH", "owner": "NEUTRAL", "province_type": "WATER", "supply_center": "false", "neighbors": [ "NRG", "EDI", "YOR", "LON", "ENG", "BEL", "HOL", "HEL", "DEN", "SKA", "NWY" ] },
    { "name": "Norwegian Sea", "abbr": "NRG", "owner": "NEUTRAL", "province_type": "WATER", "supply_center": "false", "neighbors": [ "NAT", "CLY", "EDI", "NTH", "NWY", "BAR" ] },
    { "name": "Skagerrak", "abbr": "SKA", "owner": "NEUTRAL", "province_type": "WATER", "supply_center": "false", "neighbors": [ "NWY", "NTH", "DEN", "SWE" ] },
    { "name": "Tyrrhenian Sea", "abbr": "TYN", "owner": "NEUTRAL", "province_type": "WATER", "supply_center": "false", "neighbors": [ "GOL", "WES", "TUN", "ION", "NAP", "ROM", "TUS" ] },
    { "name": "Western Mediterranean", "abbr": "WES", "owner": "NEUTRAL", "province_type": "WATER", "supply_center": "false", "neighbors": [ "GOL", "SPA", "MID", "NAF", "TUN", "TYN" ] }
]"""
